const mongoose=require('mongoose');
const appointmentSchema=new mongoose.Schema({
    visitor:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Visitor',
        required:true
    },
    host:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    purpose:{
        type:String,
        required:true
    },
    visitdate:{
        type:Date,
        required:true
    },
    status:{
        type:String,
        enum:['pending','approved','rejected'],
        default:'pending'
    },
    statusHistory:{
        type:[{
            status:{
                type:String,
                enum:['pending','approved','rejected'],
                required:true
            },
            changedAt:{
                type:Date,
                default:Date.now
            },
            changedBy:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'User'
            },
            changedByRole:{
                type:String
            }
        }],
        default:[]
    }
},{
    timestamps:true
});
module.exports=mongoose.model('Appointment',appointmentSchema);